import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClasses = `${inter.className} flex flex-col h-screen`;
  return (
    <html lang="en">
      <body className={bodyClasses}>
        <HeaderComponent />
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
