import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/layout/header";
import NavComponent from "@/components/layout/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClasses = `${inter.className} flex flex-col h-screen`;
  return (
    <html lang="en">
      <body className={bodyClasses}>
        <HeaderComponent />
        <div className="h-full flex flex-row">
          <NavComponent />
          <div className=" p-5 flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
